use lazy_static::lazy_static;
use prometheus::{
    self, Encoder, HistogramOpts, HistogramVec, IntCounterVec, Opts, Registry, TextEncoder,
};

lazy_static! {
    pub static ref REGISTRY: Registry = Registry::new();

    pub static ref HTTP_REQUESTS_TOTAL: IntCounterVec = IntCounterVec::new(
        Opts::new("guibiao_http_requests_total", "Total HTTP requests by method and path")
            .namespace("guibiao"),
        &["method", "path"]
    ).unwrap();

    pub static ref HTTP_REQUEST_DURATION_SECONDS: HistogramVec = HistogramVec::new(
        HistogramOpts::new("guibiao_http_request_duration_seconds", "HTTP request latency")
            .namespace("guibiao")
            .buckets(vec![0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0]),
        &["method", "path"]
    ).unwrap();

    pub static ref MEASUREMENTS_RECEIVED: IntCounterVec = IntCounterVec::new(
        Opts::new("guibiao_measurements_received_total", "Sensor measurements received")
            .namespace("guibiao"),
        &["station_id"]
    ).unwrap();

    pub static ref ALERTS_GENERATED: IntCounterVec = IntCounterVec::new(
        Opts::new("guibiao_alerts_generated_total", "Alerts generated by level")
            .namespace("guibiao"),
        &["level"]
    ).unwrap();

    pub static ref WS_CONNECTIONS_ACTIVE: prometheus::IntGauge = prometheus::IntGauge::new(
        "guibiao_ws_connections_active", "Active WebSocket connections"
    ).unwrap();

    pub static ref SIMULATIONS_RUN: IntCounterVec = IntCounterVec::new(
        Opts::new("guibiao_simulations_run_total", "Optical simulations executed")
            .namespace("guibiao"),
        &["station_id"]
    ).unwrap();

    pub static ref MC_ANALYSES_RUN: IntCounterVec = IntCounterVec::new(
        Opts::new("guibiao_monte_carlo_analyses_total", "Monte Carlo analyses executed")
            .namespace("guibiao"),
        &["station_id"]
    ).unwrap();
}

pub fn init() {
    REGISTRY.register(Box::new(HTTP_REQUESTS_TOTAL.clone())).unwrap();
    REGISTRY.register(Box::new(HTTP_REQUEST_DURATION_SECONDS.clone())).unwrap();
    REGISTRY.register(Box::new(MEASUREMENTS_RECEIVED.clone())).unwrap();
    REGISTRY.register(Box::new(ALERTS_GENERATED.clone())).unwrap();
    REGISTRY.register(Box::new(WS_CONNECTIONS_ACTIVE.clone())).unwrap();
    REGISTRY.register(Box::new(SIMULATIONS_RUN.clone())).unwrap();
    REGISTRY.register(Box::new(MC_ANALYSES_RUN.clone())).unwrap();
}

pub async fn metrics_handler() -> impl axum::response::IntoResponse {
    let encoder = TextEncoder::new();
    let metric_families = REGISTRY.gather();
    let mut buffer = Vec::new();
    encoder.encode(&metric_families, &mut buffer).unwrap();
    (
        axum::http::StatusCode::OK,
        [(axum::http::header::CONTENT_TYPE, "text/plain; version=0.0.4")],
        buffer,
    )
}
